### ISSUE TITLE
How to connect to our Jetbrains Account without a web browser ?

### ISSUE THREAD

**Issue by cempack** [binhex/arch-goland#1]
Hi! So I just tried out your project but found no bundled web browser to be able to connect to my JetBrains account :/
Very cool project, by the way!

![CleanShot 2024-06-28 at 15 53 15](https://github.com/binhex/arch-goland/assets/73651345/2f79b9cd-fa1e-4dd2-b83b-6905592b3937)

**Comment by binhex** [comment]
its a good question, i THINK you can do it without a browser by clicking on the 'Troubles?' link in the screenshot above, but in any case i have decided to include a web browser (firefox) in the next release which will be out shortly.

**Comment by cempack** [comment]
> its a good question, i THINK you can do it without a browser by clicking on the 'Troubles?' link in the screenshot above, but in any case i have decided to include a web browser (firefox) in the next release which will be out shortly.

Awesome, thanks! :)

**Comment by cempack** [comment]
Hello, sorry to bother again, I wondered if the update about the browser came out and if then I should close this issue.

**Comment by binhex** [comment]
yes it did
